/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author HP Desktop
 */
public class ActualizarVideojuego extends javax.swing.JPanel {

    /**
     * Creates new form ActualizarVideojuego
     */
    private int codigoVideoJuego;
    public ActualizarVideojuego() {
        initComponents();
        ocultar.setVisible(false);
        jPanel_actualizar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_actvideojuego = new javax.swing.JPanel();
        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_rut = new javax.swing.JLabel();
        jTextField_codigo = new javax.swing.JTextField();
        jSeparator_rut = new javax.swing.JSeparator();
        jPanel_buscar = new javax.swing.JPanel();
        jLabel_buscar = new javax.swing.JLabel();
        jPanel_actualizar = new javax.swing.JPanel();
        jLabel_actualizar = new javax.swing.JLabel();
        jPanel_menu1 = new javax.swing.JPanel();
        jLabel_menu1 = new javax.swing.JLabel();
        ocultar = new javax.swing.JPanel();
        jLabel_nombre = new javax.swing.JLabel();
        jTextField_version = new javax.swing.JTextField();
        jSeparator_nombre = new javax.swing.JSeparator();
        jLabel_correo = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jSeparator_correo = new javax.swing.JSeparator();
        jLabel_comuna = new javax.swing.JLabel();
        jTextField_fecha = new javax.swing.JTextField();
        jSeparator_comuna = new javax.swing.JSeparator();
        jLabel_direccion = new javax.swing.JLabel();
        jTextField_categoria = new javax.swing.JTextField();
        jSeparator_direccion = new javax.swing.JSeparator();
        jLabel_telefono = new javax.swing.JLabel();
        jTextField_genero = new javax.swing.JTextField();
        jSeparator_telefono = new javax.swing.JSeparator();
        jLabel_fNac = new javax.swing.JLabel();
        jTextField_precio = new javax.swing.JTextField();
        jSeparator_fNac = new javax.swing.JSeparator();

        jPanel_actvideojuego.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_actvideojuego.setForeground(new java.awt.Color(51, 51, 51));
        jPanel_actvideojuego.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setText("Actualizar VideoJuego");
        jPanel_actvideojuego.add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        jLabel_rut.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_rut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_rut.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_rut.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_rut.setText("Codigo:");
        jPanel_actvideojuego.add(jLabel_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 130, -1));

        jTextField_codigo.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_codigo.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_codigo.setText("0001");
        jTextField_codigo.setBorder(null);
        jPanel_actvideojuego.add(jTextField_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 270, -1));
        jPanel_actvideojuego.add(jSeparator_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 270, 10));

        jPanel_buscar.setBackground(new java.awt.Color(0, 153, 153));

        jLabel_buscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_buscar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_buscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_buscar.setText("Buscar");
        jLabel_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_buscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_buscarLayout = new javax.swing.GroupLayout(jPanel_buscar);
        jPanel_buscar.setLayout(jPanel_buscarLayout);
        jPanel_buscarLayout.setHorizontalGroup(
            jPanel_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_buscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_buscarLayout.setVerticalGroup(
            jPanel_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_buscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_actvideojuego.add(jPanel_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        jPanel_actualizar.setBackground(new java.awt.Color(0, 153, 153));

        jLabel_actualizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_actualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_actualizar.setText("Actualizar");
        jLabel_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_actualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_actualizarLayout = new javax.swing.GroupLayout(jPanel_actualizar);
        jPanel_actualizar.setLayout(jPanel_actualizarLayout);
        jPanel_actualizarLayout.setHorizontalGroup(
            jPanel_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_actualizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_actualizarLayout.setVerticalGroup(
            jPanel_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_actualizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_actvideojuego.add(jPanel_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, -1));

        jPanel_menu1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel_menu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_menu1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_menu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_menu1.setText("Atras");
        jLabel_menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_menu1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_menu1Layout = new javax.swing.GroupLayout(jPanel_menu1);
        jPanel_menu1.setLayout(jPanel_menu1Layout);
        jPanel_menu1Layout.setHorizontalGroup(
            jPanel_menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel_menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_menu1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel_menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel_menu1Layout.setVerticalGroup(
            jPanel_menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(jPanel_menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_menu1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel_menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel_actvideojuego.add(jPanel_menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        ocultar.setBackground(new java.awt.Color(51, 51, 51));
        ocultar.setForeground(new java.awt.Color(51, 51, 51));
        ocultar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_nombre.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_nombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_nombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nombre.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_nombre.setText("Version:");
        ocultar.add(jLabel_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 130, -1));

        jTextField_version.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_version.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_version.setBorder(null);
        ocultar.add(jTextField_version, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 270, -1));
        ocultar.add(jSeparator_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 270, 10));

        jLabel_correo.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_correo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_correo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_correo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_correo.setText("Nombre:");
        ocultar.add(jLabel_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, -1));

        jTextField_nombre.setEditable(false);
        jTextField_nombre.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_nombre.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_nombre.setBorder(null);
        ocultar.add(jTextField_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 270, -1));
        ocultar.add(jSeparator_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 270, 10));

        jLabel_comuna.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_comuna.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_comuna.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_comuna.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_comuna.setText("Fecha:");
        ocultar.add(jLabel_comuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 130, -1));

        jTextField_fecha.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_fecha.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_fecha.setBorder(null);
        ocultar.add(jTextField_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 270, -1));
        ocultar.add(jSeparator_comuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 270, 10));

        jLabel_direccion.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_direccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_direccion.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_direccion.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_direccion.setText("Categoria:");
        ocultar.add(jLabel_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 130, -1));

        jTextField_categoria.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_categoria.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_categoria.setBorder(null);
        ocultar.add(jTextField_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 270, -1));
        ocultar.add(jSeparator_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 270, 10));

        jLabel_telefono.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_telefono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_telefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_telefono.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_telefono.setText("Genero:");
        ocultar.add(jLabel_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 130, -1));

        jTextField_genero.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_genero.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_genero.setBorder(null);
        ocultar.add(jTextField_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 270, -1));
        ocultar.add(jSeparator_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 270, 10));

        jLabel_fNac.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_fNac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_fNac.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_fNac.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_fNac.setText("Precio:");
        ocultar.add(jLabel_fNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 130, -1));

        jTextField_precio.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_precio.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_precio.setBorder(null);
        ocultar.add(jTextField_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 270, -1));
        ocultar.add(jSeparator_fNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 270, 10));

        jPanel_actvideojuego.add(ocultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 480, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jPanel_actvideojuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jPanel_actvideojuego, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_menu1MouseClicked
        Adm_Videojuego adm_Videojuego = new Adm_Videojuego();
        adm_Videojuego.setSize(660, 460);
        adm_Videojuego.setLocation(0,0);

        jPanel_actvideojuego.removeAll();
        jPanel_actvideojuego.add(adm_Videojuego,new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        jPanel_actvideojuego.revalidate();
        jPanel_actvideojuego.repaint();
    }//GEN-LAST:event_jLabel_menu1MouseClicked

    private void jLabel_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_actualizarMouseClicked
        // Guardar los datos nuevos
        String nombre=jTextField_nombre.getText();
        String version=jTextField_version.getText();
        String fecha=jTextField_fecha.getText();
        String categoria=jTextField_categoria.getText();
        String genero=jTextField_genero.getText();
        String p=jTextField_precio.getText();
        int precio = Integer.valueOf(p);
        try{
            Visualizador.sistema.actualizarVideoJuego(codigoVideoJuego, nombre, version, fecha, categoria, genero, precio);
            JOptionPane.showMessageDialog(null,"Datos actualizados");
            ocultar.setVisible(false);
            jPanel_actualizar.setVisible(false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jLabel_actualizarMouseClicked

    private void jLabel_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_buscarMouseClicked
        //Buscar al usuario segun el codigo
        String c = jTextField_codigo.getText();
        int code = Integer.valueOf(c);
        int posicion = Visualizador.sistema.buscarVideoJuego(code);
        if(posicion == -1){
            JOptionPane.showMessageDialog(null,"No existe un VideoJuego con este codigo.");
        }else{
            codigoVideoJuego=posicion;
            String [] datosVideojuego = Visualizador.sistema.obtenerDatosVideoJuego(codigoVideoJuego);
            String nombre = datosVideojuego[0];
            String version = datosVideojuego[1];
            String fecha = datosVideojuego[2];
            String categoria = datosVideojuego[3];
            String genero = datosVideojuego[4];
            String precio = datosVideojuego[5];
            jTextField_nombre.setText(nombre);
            jTextField_version.setText(version);
            jTextField_fecha.setText(fecha);
            jTextField_categoria.setText(categoria);
            jTextField_genero.setText(genero);
            jTextField_precio.setText(precio);
            
            ocultar.setVisible(true);
            jPanel_actualizar.setVisible(true);
        }
        

    }//GEN-LAST:event_jLabel_buscarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_actualizar;
    private javax.swing.JLabel jLabel_buscar;
    private javax.swing.JLabel jLabel_comuna;
    private javax.swing.JLabel jLabel_correo;
    private javax.swing.JLabel jLabel_direccion;
    private javax.swing.JLabel jLabel_fNac;
    private javax.swing.JLabel jLabel_menu1;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_rut;
    private javax.swing.JLabel jLabel_telefono;
    private javax.swing.JPanel jPanel_actualizar;
    private javax.swing.JPanel jPanel_actvideojuego;
    private javax.swing.JPanel jPanel_buscar;
    private javax.swing.JPanel jPanel_menu1;
    private javax.swing.JSeparator jSeparator_comuna;
    private javax.swing.JSeparator jSeparator_correo;
    private javax.swing.JSeparator jSeparator_direccion;
    private javax.swing.JSeparator jSeparator_fNac;
    private javax.swing.JSeparator jSeparator_nombre;
    private javax.swing.JSeparator jSeparator_rut;
    private javax.swing.JSeparator jSeparator_telefono;
    private javax.swing.JTextField jTextField_categoria;
    private javax.swing.JTextField jTextField_codigo;
    private javax.swing.JTextField jTextField_fecha;
    private javax.swing.JTextField jTextField_genero;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_precio;
    private javax.swing.JTextField jTextField_version;
    private javax.swing.JPanel ocultar;
    // End of variables declaration//GEN-END:variables
}
