/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author reeso
 */
public class ActualizarArriendo extends javax.swing.JPanel {
    
    private String buscado_por;
    private String rut;
    private int codigo;
    private DefaultTableModel tabla;
    /**
     * Creates new form IngresarUsuario
     */
    public ActualizarArriendo() {
        initComponents();
        jScrollPane1.setVisible(false);
        jTextField_fechaE.setVisible(false);
        jLabel_fechaE.setVisible(false);
        jSeparator_fechaE.setVisible(false);
        jPanel_actualizar.setVisible(false);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        tabla = model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actualizarArriendo = new javax.swing.JPanel();
        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_rut = new javax.swing.JLabel();
        jTextField_rutCliente = new javax.swing.JTextField();
        jSeparator_rut = new javax.swing.JSeparator();
        jLabel_codigo = new javax.swing.JLabel();
        jTextField_codigoVideoJuego = new javax.swing.JTextField();
        jSeparator_codigo = new javax.swing.JSeparator();
        jPanel_buscar_rut = new javax.swing.JPanel();
        jLabel_registrar1 = new javax.swing.JLabel();
        jPanel_buscar_codigo = new javax.swing.JPanel();
        jLabel_buscar_segun_code = new javax.swing.JLabel();
        jPanel_menu = new javax.swing.JPanel();
        jLabel_menu = new javax.swing.JLabel();
        jPanel_actualizar = new javax.swing.JPanel();
        jLabel_actualizar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ocultar = new javax.swing.JPanel();
        jLabel_fechaE = new javax.swing.JLabel();
        jSeparator_fechaE = new javax.swing.JSeparator();
        jTextField_fechaE = new javax.swing.JTextField();

        actualizarArriendo.setBackground(new java.awt.Color(51, 51, 51));
        actualizarArriendo.setPreferredSize(new java.awt.Dimension(610, 460));
        actualizarArriendo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setText("Actualizar Arriendo");
        actualizarArriendo.add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        jLabel_rut.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_rut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_rut.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_rut.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_rut.setText("Rut cliente:");
        actualizarArriendo.add(jLabel_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 130, -1));

        jTextField_rutCliente.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_rutCliente.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_rutCliente.setText("00.000.000-K");
        jTextField_rutCliente.setBorder(null);
        actualizarArriendo.add(jTextField_rutCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 270, -1));
        actualizarArriendo.add(jSeparator_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 270, 10));

        jLabel_codigo.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_codigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_codigo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_codigo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_codigo.setText("Codigo videojuego:");
        actualizarArriendo.add(jLabel_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 130, -1, -1));

        jTextField_codigoVideoJuego.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_codigoVideoJuego.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_codigoVideoJuego.setText("0001");
        jTextField_codigoVideoJuego.setBorder(null);
        actualizarArriendo.add(jTextField_codigoVideoJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 270, -1));
        actualizarArriendo.add(jSeparator_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 270, 10));

        jPanel_buscar_rut.setBackground(new java.awt.Color(0, 153, 153));

        jLabel_registrar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_registrar1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_registrar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_registrar1.setText("Buscar por rut");
        jLabel_registrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_registrar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_buscar_rutLayout = new javax.swing.GroupLayout(jPanel_buscar_rut);
        jPanel_buscar_rut.setLayout(jPanel_buscar_rutLayout);
        jPanel_buscar_rutLayout.setHorizontalGroup(
            jPanel_buscar_rutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_buscar_rutLayout.createSequentialGroup()
                .addComponent(jLabel_registrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_buscar_rutLayout.setVerticalGroup(
            jPanel_buscar_rutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_buscar_rutLayout.createSequentialGroup()
                .addComponent(jLabel_registrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        actualizarArriendo.add(jPanel_buscar_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 180, 33));

        jPanel_buscar_codigo.setBackground(new java.awt.Color(0, 153, 153));

        jLabel_buscar_segun_code.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_buscar_segun_code.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_buscar_segun_code.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_buscar_segun_code.setText("Buscar por codigo");
        jLabel_buscar_segun_code.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_buscar_segun_codeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_buscar_codigoLayout = new javax.swing.GroupLayout(jPanel_buscar_codigo);
        jPanel_buscar_codigo.setLayout(jPanel_buscar_codigoLayout);
        jPanel_buscar_codigoLayout.setHorizontalGroup(
            jPanel_buscar_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
            .addGroup(jPanel_buscar_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_buscar_codigoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel_buscar_segun_code, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel_buscar_codigoLayout.setVerticalGroup(
            jPanel_buscar_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel_buscar_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_buscar_codigoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel_buscar_segun_code, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        actualizarArriendo.add(jPanel_buscar_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, 33));

        jPanel_menu.setBackground(new java.awt.Color(0, 153, 153));

        jLabel_menu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_menu.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_menu.setText("Atras");
        jLabel_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_menuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_menuLayout = new javax.swing.GroupLayout(jPanel_menu);
        jPanel_menu.setLayout(jPanel_menuLayout);
        jPanel_menuLayout.setHorizontalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_menuLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel_menuLayout.setVerticalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_menuLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        actualizarArriendo.add(jPanel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        jPanel_actualizar.setBackground(new java.awt.Color(0, 153, 153));

        jLabel_actualizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_actualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_actualizar.setText("Actualizar");
        jLabel_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_actualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_actualizarLayout = new javax.swing.GroupLayout(jPanel_actualizar);
        jPanel_actualizar.setLayout(jPanel_actualizarLayout);
        jPanel_actualizarLayout.setHorizontalGroup(
            jPanel_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_actualizarLayout.createSequentialGroup()
                .addComponent(jLabel_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_actualizarLayout.setVerticalGroup(
            jPanel_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_actualizarLayout.createSequentialGroup()
                .addComponent(jLabel_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        actualizarArriendo.add(jPanel_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 100, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rut", "Codigo", "Fecha de entrega"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        actualizarArriendo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 500, 110));

        ocultar.setBackground(new java.awt.Color(51, 51, 51));
        ocultar.setPreferredSize(new java.awt.Dimension(610, 460));
        ocultar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_fechaE.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_fechaE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_fechaE.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_fechaE.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_fechaE.setText("Fecha entrega:");
        ocultar.add(jLabel_fechaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 130, -1));
        ocultar.add(jSeparator_fechaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 270, 10));

        jTextField_fechaE.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_fechaE.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_fechaE.setText("DD/MM/YY");
        jTextField_fechaE.setBorder(null);
        ocultar.add(jTextField_fechaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 270, -1));

        actualizarArriendo.add(ocultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 420, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(actualizarArriendo, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(actualizarArriendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_menuMouseClicked
        Menu_vendedor menu_admin = new Menu_vendedor();
        menu_admin.setSize(660, 460);
        menu_admin.setLocation(0,0);

        actualizarArriendo.removeAll();
        actualizarArriendo.add(menu_admin,new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        actualizarArriendo.revalidate();
        actualizarArriendo.repaint();
    }//GEN-LAST:event_jLabel_menuMouseClicked

    private void jLabel_registrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_registrar1MouseClicked
        String rutCliente = jTextField_rutCliente.getText();
        verificarCamposEnBlanco(rutCliente, "rutCliente");
        
        int posicion = Visualizador.sistema.buscarArriendo(rutCliente);
        if(posicion == -1){
            JOptionPane.showMessageDialog(null,"Este Usuario no tiene arriendos.");
        }else{
            eliminarDatosTable();
            jScrollPane1.setVisible(true);
            
            List <String[]> matriz = Visualizador.sistema.obtenerDatosArrindo_segun_rut(rutCliente);
            
            for(int i = 0;i<matriz.size();i++){
                tabla.addRow(matriz.get(i));
            }

            rut = rutCliente;
            buscado_por = "rut";
            jPanel_actualizar.setVisible(true);
        }

    }//GEN-LAST:event_jLabel_registrar1MouseClicked

    private void jLabel_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_actualizarMouseClicked
        List <Vector> matriz =tabla.getDataVector();
        Visualizador.sistema.actualizarArriendo(matriz);
        jScrollPane1.setVisible(false);
        jPanel_actualizar.setVisible(false);
        /*
        String fecha_de_entrega = tabla.getValueAt(1, 1)+"";

        try{
            //Visualizador.sistema.ingresarArriendo(codigoVideoJuego, rutCliente);
            JOptionPane.showMessageDialog(null,"Usuario ingresado.");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());

        }*/
    }//GEN-LAST:event_jLabel_actualizarMouseClicked
    public void verificarCamposEnBlanco(String campo,String nombre){
        if(campo.equals("")){
            JOptionPane.showMessageDialog(null,"La "+nombre+" no puede estar en blanco.");
        }
    }
    private void jLabel_buscar_segun_codeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_buscar_segun_codeMouseClicked
        String codigoVideoJuego = jTextField_codigoVideoJuego.getText();
        verificarCamposEnBlanco(codigoVideoJuego, "codigoVideoJuego");
        try{
            int code = Integer.parseInt(codigoVideoJuego);
            int posicion = Visualizador.sistema.buscarArriendo(code);
            if(posicion == -1){
                JOptionPane.showMessageDialog(null,"No existen arriendos de este videoJuego.");
            }else{
                jTextField_codigoVideoJuego.setVisible(true);
                jLabel_codigo.setVisible(true);
                jSeparator_codigo.setVisible(true);
                codigo = code;
                buscado_por = "codigo";
            }
        }catch(Exception e){
            throw new NullPointerException("El codigo del viedeoJuego debe ser un valor numerico.");
        }
    }//GEN-LAST:event_jLabel_buscar_segun_codeMouseClicked
    
    private void eliminarDatosTable(){
        int fila = jTable1.getRowCount();
        for(int i=fila-1;i>=0;i--){
            tabla.removeRow(i);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actualizarArriendo;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_actualizar;
    private javax.swing.JLabel jLabel_buscar_segun_code;
    private javax.swing.JLabel jLabel_codigo;
    private javax.swing.JLabel jLabel_fechaE;
    private javax.swing.JLabel jLabel_menu;
    private javax.swing.JLabel jLabel_registrar1;
    private javax.swing.JLabel jLabel_rut;
    private javax.swing.JPanel jPanel_actualizar;
    private javax.swing.JPanel jPanel_buscar_codigo;
    private javax.swing.JPanel jPanel_buscar_rut;
    private javax.swing.JPanel jPanel_menu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator_codigo;
    private javax.swing.JSeparator jSeparator_fechaE;
    private javax.swing.JSeparator jSeparator_rut;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_codigoVideoJuego;
    private javax.swing.JTextField jTextField_fechaE;
    private javax.swing.JTextField jTextField_rutCliente;
    private javax.swing.JPanel ocultar;
    // End of variables declaration//GEN-END:variables
}
